apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ion-sfu-gstreamer-send.fullname" . }}
type: Opaque
data:
  teamdomain: {{ default "NOTSET" .Values.teamdomain | b64enc | quote }}
  policyaud: {{ default "NOTSET" .Values.policyaud | b64enc | quote }}
