apiVersion: v1
kind: Service
metadata:
  name: {{ include "ion-sfu-gstreamer-send.fullname" . }}
  labels:
    {{- include "ion-sfu-gstreamer-send.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "ion-sfu-gstreamer-send.selectorLabels" . | nindent 4 }}
