apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ion-sfu-gstreamer-send.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.videosrcport }}
      targetPort: {{ .Values.config.videosrcport }}
      protocol: UDP
      name: videosrcport
    - port: {{ .Values.config.audiosrcport }}
      targetPort: {{ .Values.config.audiosrcport }}
      protocol: UDP
      name: audiosrcsort 
  selector:
    {{- include "ion-sfu-gstreamer-send.selectorLabels" . | nindent 4 }}
