# Default values for ion-sfu-gstreamer-send.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  videosrcport: 10000
  audiosrcport: 11000
  ionsfu:
    address: "ion-sfu:50051"
  turn:  
    address: "ion-sfu-turn:3478"
    user: "pion"
    pass: "ion"
  gstreamer:  
    debug: "2"
    audio:
      codec: "opus"
      source: ""
    video:
      codec: "bare"
      source: "udpsrc port=10000 ! queue ! h264parse ! rtph264pay config-interval=10 pt=96 ! rtph264depay ! avdec_h264 ! video/x-raw,format=I420 ! x264enc speed-preset=ultrafast tune=zerolatency key-int-max=20 ! video/x-h264,stream-format=byte-stream ! appsink name=appsink"

replicaCount: 1

image:
  repository: sordfish/ion-sfu-gstreamer-send
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ion-sfu-gstreamer-send"


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 10000
  targetport: 10000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}